#If true, entities will be affected by gravity.
doEntityGravity = true
#Do gravity for mobs, players etc.
doLivingEntityGravity = true
acidRainBurns = true
doOxygen = true
#Do sound suppression in orbit dimensions. If it gets annoying, you can turn it off.
doSpaceMuffler = true
oxygenTankSize = 500
hammerDurability = 64
giveAstroduxAtSpawn = false
oxygenBarXOffset = 0
oxygenBarYOffset = 0
oxygenBarScale = 1.0
energyBarXOffset = 0
energyBarYOffset = 0
energyBarScale = 1.0
orbitGravity = 3.26
oxygenDamage = 1
freezeDamage = 1
heatDamage = 2
acidRainDamage = 3
allowFlagImages = true
#A list of planets that should be disabled. This is a comma-separated list of planet ids.
disabledPlanets = ""
#Prevents stuff like gravity and oxygen checks in the overworld as that's normally not used in Ad Astra. enable if you're making an addon or something that transforms the overworld into some sort of planet.
avoidOverworldChecks = true
#Enable/Disable lunarian and lunarian wandering trader's default trades. Apply to lunarian spawned after this value changed.
enabledLunarianDefaultTrades = true

[spawning]
	spawnCorruptedLunarians = true
	spawnStarCrawlers = true
	spawnMartianRaptors = true
	spawnMoglers = true
	spawnSulfurCreepers = true
	spawnLunarianWanderingTrader = true

[spaceSuit]
	spaceSuitTankSize = 50000
	netheriteSpaceSuitTankSize = 20000
	netheriteSpaceSuitHasFireResistance = true
	#The speed when flying forward.
	jetSuitSpeed = 1.4
	#The speed when idle flying up.
	jetSuitUpwardsSpeed = 1.0
	jetSuitEnergyPerTick = 160
	jetSuitTankSize = 40000
	jetSuitMaxEnergy = 1000000
	enableJetSuitFlight = true
	jetSuitProtectionMultiplier = 1.5
	jetSuitArmorToughness = 9
	spawnJetSuitParticles = true
	#Custom hand rendering may interfere with Shaders
	renderCustomFirstPersonHand = true

[vehicles]
	#The velocity to trigger a vehicle explosion while falling.
	fallingExplosionThreshold = -1.2
	#How much the explosion should be multiplied by when the vehicle has fallen.
	fallingExplosionMultiplier = 0.7
	gravity = -2.0
	#Should the camera move in 3rd person in the rocket and lander for a better view?
	moveCameraInVehicle = true

	[vehicles.lander]
		boosterThreshold = -0.1
		boosterSpeed = 0.1

	[vehicles.rover]
		explodeRoverInLava = true
		fuelPerSecond = 10
		turnSpeed = 3.0
		maxTurnSpeed = 6.0
		deceleration = 0.9
		minSpeed = -0.2
		maxSpeed = 0.3
		tankSize = 3000

	[vehicles.rocket]
		atmosphereLeave = 450
		countDownTicks = 160
		acceleration = 0.01
		maxSpeed = 0.7
		entitiesBurnUnderRocket = true
		tankSize = 3000
		fuelLaunchCost = 3000
		efficientFuelLaunchCost = 1000
		takeDamageInRocket = true

[coalGenerator]
	maxEnergy = 9000
	energyPerTick = 10

[compressor]
	maxEnergy = 9000
	energyPerTick = 10

[fuelRefinery]
	maxEnergy = 9000
	energyPerTick = 30
	tankSize = 3000

[oxygenLoader]
	maxEnergy = 9000
	energyPerTick = 10
	tankSize = 30000

[oxygenDistributor]
	maxEnergy = 20000
	fluidConversionEnergyPerTick = 5
	tankSize = 60000
	#How many blocks the distributor can distribute oxygen in. Be careful increasing this number, as it can reduce server performance significantly. If you are adamant about increasing this value, consider increasing the Oxygen Loader refresh ticks so the server is not constantly checking thousands of blocks.
	#Range: 1 ~ 50000
	maxBlockChecks = 3000
	#How often the oxygen loader checks if the structure is sealed. Performing this operation too often can kill server TPS, so be wary.
	#Range: 0 ~ 500
	refreshTicks = 60
	#Increases the oxygen requirements as the distributor covers more blocks.
	oxygenMultiplier = 1.0
	#Increases the energy requirements as the distributor covers more blocks.
	energyMultiplier = 3.0

[solarPanel]
	maxEnergy = 1800000
	energyMultiplier = 10.0

[waterPump]
	maxEnergy = 9000000
	energyPerTick = 100
	tankSize = 60000
	transferPerTick = 10000
	deleteWaterBelowWaterPump = true

[energizer]
	maxEnergy = 200000000
	energyPerTick = 6000

[cryoFreezer]
	maxEnergy = 300000
	energyPerTick = 18
	tankSize = 30000

