
#Void Crystal Ore Worldgen
[void_crystal_ore]
	#Enable/Disable Void Crystal ore
	VoidCrystalOreEnabled = true
	#Min Y level
	#Range: -64 ~ -20
	minY = -64
	#Max Y Level
	#Range: -60 ~ 0
	maxY = -54
	#Ore vein count
	#Range: 1 ~ 40
	veinCount = 20
	#Ore vein size
	#Range: 1 ~ 40
	veinSize = 3

